config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :monsters
    resources :monster_teams
  end

  resources :monster_teams
  resources :monsters
  devise_for :users, controller: { omniauth_callbacks: 'users/omniauth_callbacks'  }
  root 'pages#index'
end

app/models/api_client.rb
require 'securerandom'

class ApiClient < ActiveRecord::Base
  validates :title, presence: true

  before_create :set_token

  private

  def set_token
    self.token = SecureRandom.uuid
  end
end

app/models/monster.rb
class Monster < ActiveRecord::Base
  self.inheritance_column = nil

  TYPES = %w(fire water earth electric wind)

  belongs_to :user
  belongs_to :monster_team

  validates :name, :type, :power, presence: true
  validates :type, inclusion: { in: TYPES }
  validate do |monster|
    if monster.user && monster.user.monsters.count >= 20
      errors.add(:base, 'User can have maximum 20 monsters')
    end
  end

  before_save :set_weakness

  private

  def set_weakness
    current_type_index = TYPES.index(self.type)
    if self.type == TYPES.last
      self.weakness = TYPES.first
    else
      self.weakness = TYPES[current_type_index + 1]
    end
  end
end

app/models/monster_team.rb
class MonsterTeam < ActiveRecord::Base
  belongs_to :user
  has_many :monsters

  validates :name, presence: true
  validate do |monster_team|
    if monster_team.monsters && monster_team.monsters.size != 3
      errors.add(:base, 'Monster team should consists of 3 monsters')
    end
  end

  validate do |monster_team|
    if monster_team.user && monster_team.user.monster_teams.size >= 3
      errors.add(:base, 'User is not allowed to have more than three monster teams')
    end
  end

  scope :for, -> (email) { joins(:user).where(users: { email: email }).includes(:monsters) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :monsters
  has_many :monster_teams

  def self.from_facebook(auth)
    where( provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email    = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_request
  respond_to :json

  private

  def authenticate_request
    unless ApiClient.where(token: params[:token]).present?
      render json: { error: 'Unauthorized' }
    end
  end
end

app/controllers/api/monster_teams_controller.rb
module Api
  class MonsterTeamsController < ApiController
    def index
      render json: MonsterTeam.for(params[:email]),
             each_serializer: MonsterTeamSerializer
    end

    def show
      monster_team = MonsterTeam.includes(:monsters).find(params[:id])
      render json: monster_team, serializer: MonsterTeamSerializer
    end

    def create
      monster_team = MonsterTeam.new(monster_team_params)

      if monster_team.save
        render json: monster_team, serializer: MonsterTeamSerializer
      else
        render json: { monster_team: { errors: monster_team.errors } },
               status: 422
      end
    end

    def update
      monster_team = MonsterTeam.find(params[:id])

      if monster_team.update(monster_team_params)
        render json: monster_team, serializer: MonsterTeamSerializer
      else
        render json: { monster_team: { errors: monster_team.errors } },
               status: 422
      end
    end

    def destroy
      monster_team = MonsterTeam.find(params[:id])
      monster_team.destroy
      render nothing: true
    end

    private

    def monster_team_params
      params.require(:monster_team).permit(:name, :user_id, monster_ids: [])
    end
  end
end

app/controllers/api/monsters_controller.rb
module Api
  class MonstersController < ApiController
    def index
      monsters = Monster.joins(:user).where(users: { email: params[:email] })
      render json: monsters, each_serializer: MonsterSerializer
    end

    def show
      monster = Monster.find(params[:id])
      render json: monster, serializer: MonsterSerializer
    end

    def create
      monster = Monster.new(monster_params)

      if monster.save
        render json: monster, serializer: MonsterSerializer
      else
        render json: { monster: { errors: monster.errors } },
               status: 422
      end
    end

    def update
      monster = Monster.find(params[:id])

      if monster.update(monster_params)
        render json: monster, serializer: MonsterSerializer
      else
        render json: { monster: { errors: monster.errors } },
               status: 422
      end
    end

    def destroy
      monster = Monster.find(params[:id])
      monster.destroy
      render nothing: true
    end

    private

    def monster_params
      params.require(:monster).permit(:name, :power, :type, :user_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/monster_teams_controller.rb
class MonsterTeamsController < ApplicationController
  before_action :monster_team, only: [:show, :edit, :update, :destroy]

  def index
    @monster_teams = current_user.monster_teams
  end

  def show
  end

  def new
    @monster_team = current_user.monster_teams.new
  end

  def edit
  end

  def create
    @monster_team = current_user.monster_teams.new(monster_team_params)

    if @monster_team.save
      redirect_to @monster_team, notice: 'Monster team was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monster_team.update(monster_team_params)
      redirect_to @monster_team, notice: 'Monster team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monster_team.destroy
    redirect_to monster_teams_url, notice: 'Monster team was successfully destroyed.'
  end

  private
    def monster_team
      @monster_team = current_user.monster_teams.find(params[:id])
    end

    def monster_team_params
      params.require(:monster_team).permit(:name, monster_ids: [])
    end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :monster, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.monsters.ransack(params[:q])
    @monsters = @q.result(distinct: true)
  end

  def show
  end

  def new
    @monster = current_user.monsters.new
  end

  def edit
  end

  def create
    @monster = current_user.monsters.new(monster_params)

    if @monster.save
      redirect_to @monster, notice: 'Monster was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monster.update(monster_params)
      redirect_to @monster, notice: 'Monster was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monster.destroy
    redirect_to monsters_url, notice: 'Monster was successfully destroyed.'
  end

  private

  def monster
    @monster = current_user.monsters.find(params[:id])
  end

  def monster_params
    params.require(:monster).permit(:name, :type, :power)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def facebook
      @user = User.from_facebook(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
.row
  %nav.top-bar{ role: 'navigation' }
    .top-bar-left
      %ul.menu
        %li.menu-text= link_to 'Rubymon', root_path
        %li= link_to 'Monsters', monsters_path
        %li= link_to 'Monster Teams', monster_teams_path
    .top-bar-right
      %ul.menu
        - if user_signed_in?
          %li.menu-text= link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign In via Facebook', user_omniauth_authorize_path(:facebook)
          %li.menu-text= link_to 'Sign In', new_user_session_path
          %li= link_to 'Sign Up', new_user_registration_path, class: 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rubymon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render 'layouts/header'

    .text-center
      .notice= notice
      .alert= alert

    .row
      .medium-10.medium-offset-1.columns
        = yield

app/views/monster_teams/_form.html.haml
= form_for @monster_team do |f|
  - if @monster_team.errors.any?
    #error_explanation
      %h2= "#{pluralize(@monster_team.errors.count, "error")} prohibited this monster team from being saved:"
      %ul
        - @monster_team.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :monster_ids, 'Monsters (choose 3)'
    = f.select :monster_ids, current_user.monsters.pluck(:name, :id), { }, { multiple: true, size: 5 }
    .hint *Use CTRL on Windows and CMD on Mac to choose multiple monsters
  .actions
    = f.submit 'Save', class: 'button float-right'

app/views/monster_teams/edit.html.haml
%h1 Editing monster team

= render 'form'

= link_to 'Show', @monster_team
\|
= link_to 'Back', monster_teams_path

app/views/monster_teams/index.html.haml
%h1 Listing monster_teams

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @monster_teams.each do |monster_team|
      %tr
        %td= monster_team.name
        %td= link_to 'Show', monster_team
        %td= link_to 'Edit', edit_monster_team_path(monster_team)
        %td= link_to 'Destroy', monster_team, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Monster team', new_monster_team_path

app/views/monster_teams/new.html.haml
%h1 New monster team

= render 'form'

= link_to 'Back', monster_teams_path

app/views/monster_teams/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @monster_team.name
%p
  %b Monsters:
  = @monster_team.monsters.pluck(:name).join(', ')

= link_to 'Edit', edit_monster_team_path(@monster_team)
\|
= link_to 'Back', monster_teams_path

app/views/monsters/_form.html.haml
= form_for @monster do |f|
  - if @monster.errors.any?
    #error_explanation
      %h2= "#{pluralize(@monster.errors.count, "error")} prohibited this monster from being saved:"
      %ul
        - @monster.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :type
    = f.select :type, Monster::TYPES, prompt: 'Select Monster type'
  .field
    = f.label :power
    = f.text_field :power
  .actions
    = f.submit 'Save', class: 'button float-right'

app/views/monsters/edit.html.haml
%h1 Editing monster

= render 'form'

= link_to 'Show', @monster
\|
= link_to 'Back', monsters_path

app/views/monsters/index.html.haml
%h1 Listing monsters

%table
  %thead
    %tr
      %th= sort_link @q, :name, 'Name'
      %th= sort_link @q, :type, 'Type'
      %th= sort_link @q, :power, 'Power'
      %th= sort_link @q, :weakness, 'Weakness'
      %th
      %th
      %th

  %tbody
    - @monsters.each do |monster|
      %tr
        %td= monster.name
        %td= monster.type
        %td= monster.power
        %td= monster.weakness
        %td= link_to 'Show', monster
        %td= link_to 'Edit', edit_monster_path(monster)
        %td= link_to 'Destroy', monster, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Monster', new_monster_path

app/views/monsters/new.html.haml
%h1 New monster

= render 'form'

= link_to 'Back', monsters_path

app/views/monsters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @monster.name
%p
  %b Type:
  = @monster.type
%p
  %b Power:
  = @monster.power
%p
  %b Weakness:
  = @monster.weakness

= link_to 'Edit', edit_monster_path(@monster)
\|
= link_to 'Back', monsters_path

app/views/pages/index.html.haml
%h1.text-center Welcome to Rubymon Game